<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-3G8P0RD" ignored="0" name="Default test" tests="2" failures="1" timestamp="16 三月 2018 10:39:21 GMT" time="57.706" errors="0">
  <testcase name="LoginFailTest" time="9.872" classname="com.dream.testcases.LoginTest"/>
  <testcase name="LoginSuccessTest" time="20.556" classname="com.dream.testcases.LoginTest">
    <failure type="java.lang.AssertionError" message="查找元素异常，退出当前测试用例">
      <![CDATA[java.lang.AssertionError: 查找元素异常，退出当前测试用例at org.testng.Assert.fail(Assert.java:96)at com.dream.framework.WebElementUtils.getElement(WebElementUtils.java:57)at com.dream.framework.WebElementUtils$1.apply(WebElementUtils.java:69)at com.dream.framework.WebElementUtils$1.apply(WebElementUtils.java:1)at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)at com.dream.framework.WebElementUtils.findElement(WebElementUtils.java:67)at com.dream.framework.WebElementUtils.getText(WebElementUtils.java:87)at com.dream.pages.MainPage.getUserName(MainPage.java:29)at com.dream.testcases.LoginTest.LoginSuccessTest(LoginTest.java:43)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- LoginSuccessTest -->
</testsuite> <!-- Default test -->
